name: employee_tracker
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.5+3
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  localstorage: ^4.0.0
  ffi: ^2.1.4
  get_storage: ^2.1.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  device_info_plus: ^11.4.0
  font_awesome_flutter: ^10.8.0
  flutter_image_compress: ^2.4.0
  path_provider: ^2.1.5
  path: ^1.9.1
  cross_file: ^0.3.4+2
  permission_handler: ^12.0.0+1
  google_maps_flutter: ^2.12.1
  url_launcher: ^6.3.1
  percent_indicator: ^4.2.5
  latlong2: ^0.9.1
  flutter_map: ^6.0.0
  video_player: ^2.9.5
  image: ^4.5.4
  connectivity_plus: ^6.1.4
  month_picker_dialog: ^6.2.1
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # 👈 added here

flutter_icons:  # 👈 placed outside of `flutter`
  android: true
  ios: true
  image_path: "assets/splesh_Screen/staff-track.png"

flutter:
  uses-material-design: true

  assets:
    - assets/Videos/WelCome.mp4
    - assets/splesh_Screen/
    - assets/images/
    - assets/images/kingfish-logo.webp

  fonts:
    - family: MyFont
      fonts:
        - asset: assets/fonts/PoetsenOne-Regular.ttf
          weight: 700
