// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAswo57laQ_JmpR4q1dQ6SQjA1qbuZZiFU',
    appId: '1:861463887023:web:487a91840321477456685a',
    messagingSenderId: '861463887023',
    projectId: 'empattend-da378',
    authDomain: 'empattend-da378.firebaseapp.com',
    storageBucket: 'empattend-da378.firebasestorage.app',
    measurementId: 'G-YD8JKM2YX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmDZKjSFdRcoUfwgtoH5th02OSuP2gJiw',
    appId: '1:861463887023:android:3c458469d37202c956685a',
    messagingSenderId: '861463887023',
    projectId: 'empattend-da378',
    storageBucket: 'empattend-da378.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTIEFa4F7kJe-gtqjqumhJk0wefynyU0M',
    appId: '1:861463887023:ios:a4943caf4647693c56685a',
    messagingSenderId: '861463887023',
    projectId: 'empattend-da378',
    storageBucket: 'empattend-da378.firebasestorage.app',
    iosBundleId: 'com.example.employeeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCTIEFa4F7kJe-gtqjqumhJk0wefynyU0M',
    appId: '1:861463887023:ios:a4943caf4647693c56685a',
    messagingSenderId: '861463887023',
    projectId: 'empattend-da378',
    storageBucket: 'empattend-da378.firebasestorage.app',
    iosBundleId: 'com.example.employeeTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAswo57laQ_JmpR4q1dQ6SQjA1qbuZZiFU',
    appId: '1:861463887023:web:1563d122f5048ee856685a',
    messagingSenderId: '861463887023',
    projectId: 'empattend-da378',
    authDomain: 'empattend-da378.firebaseapp.com',
    storageBucket: 'empattend-da378.firebasestorage.app',
    measurementId: 'G-B868JEH4W7',
  );
}
